"""
FlyRank Backend Track — Week 1 Assignment: Build your first API endpoint

Assignment brief (from the cohort kickoff): a basic API with error handling,
returning different responses with different status codes.

This implements a full CRUD API for a "Task" resource — deliberately a bit
more than the bare minimum, structured so it's easy to extend in later weeks
(auth, background jobs, a real database) without a rewrite.

Run locally:
    uvicorn app.main:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

import asyncio
import uuid
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Response, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from fastapi.requests import Request
from dotenv import load_dotenv

from app.exceptions import TaskNotFoundError
from app.models import TaskCreate, TaskUpdate, TaskResponse
from app.repository import task_repository
from src.bg.schema import JobAccepted, JobResponse
from src.bg.settings import get_bg_settings
from src.bg.store import JobStore
from src.bg.worker import JobWorker
from src.llm.clients import LLMDisabled, LLMTimeout, LLMUnavailable
from src.llm.schema import TriageRequest
from src.llm.service import LLMInvalidOutput

load_dotenv()

# Durable job store: process-wide, safe to share (thread-locked, append-only).
bg_store = JobStore()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Start the worker pool with the API; drain it on shutdown.

    The pool is created HERE, inside the running event loop, because an
    asyncio.Queue binds itself to the loop it is first used on. A pool made
    at import time would be bound to the wrong loop and starve.

    Startup also re-enqueues jobs a previous process left unfinished
    (the "jobs run twice" case - safe, because a triage job is a pure
    function of its input message).
    """
    worker = JobWorker(bg_store, cfg=get_bg_settings())
    app.state.bg_worker = worker
    await worker.requeue_interrupted()
    tasks = [
        asyncio.create_task(worker.run())
        for _ in range(worker.cfg["worker_count"])
    ]
    yield
    for task in tasks:
        task.cancel()
    await asyncio.gather(*tasks, return_exceptions=True)

app = FastAPI(
    title="FlyRank Task API",
    description="Week 1 Backend AI Engineering assignment - a CRUD Task API with an LLM triage job (A17) executed on a background worker (BE-06).",
    version="1.0.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------
# Centralizing this here means every endpoint gets consistent error JSON
# without repeating try/except blocks in each route. This is the "error
# handling" half of the assignment brief.

@app.exception_handler(TaskNotFoundError)
async def task_not_found_handler(request: Request, exc: TaskNotFoundError):
    return JSONResponse(
        status_code=status.HTTP_404_NOT_FOUND,
        content={"error": "task_not_found", "message": str(exc)},
    )


@app.exception_handler(RequestValidationError)
async def validation_error_handler(request: Request, exc: RequestValidationError):
    title_errors = ("missing", "value_error", "string_too_short")
    has_title_error = any(
        err.get("loc") == ("body", "title") and err.get("type") in title_errors
        for err in exc.errors()
    )
    if has_title_error:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={
                "error": "validation_error",
                "message": "Title is required and must not be empty.",
            },
        )
    message_errors = ("missing", "value_error", "string_too_short", "string_too_long")
    has_message_error = any(
        err.get("loc") == ("body", "message") and err.get("type") in message_errors
        for err in exc.errors()
    )
    if has_message_error:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={
                "error": "validation_error",
                "message": "'message' is required and must be a non-empty string.",
            },
        )
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"detail": exc.errors()},
    )


# ---------------------------------------------------------------------------
# LLM error handling (A17)
# ---------------------------------------------------------------------------

@app.exception_handler(LLMTimeout)
async def llm_timeout_handler(request: Request, exc: LLMTimeout):
    return JSONResponse(
        status_code=status.HTTP_504_GATEWAY_TIMEOUT,
        content={"error": "llm_timeout", "message": str(exc)},
    )


@app.exception_handler(LLMUnavailable)
async def llm_unavailable_handler(request: Request, exc: LLMUnavailable):
    return JSONResponse(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        content={"error": "llm_unavailable", "message": str(exc)},
    )


@app.exception_handler(LLMDisabled)
async def llm_disabled_handler(request: Request, exc: LLMDisabled):
    return JSONResponse(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        content={"error": "llm_disabled", "message": str(exc)},
    )


@app.exception_handler(LLMInvalidOutput)
async def llm_invalid_output_handler(request: Request, exc: LLMInvalidOutput):
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"error": "invalid_llm_output", "message": str(exc)},
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", tags=["meta"])
def root():
    return {"name": "Task API", "version": "1.0", "endpoints": ["/tasks"]}


@app.get("/health", tags=["meta"])
def health_check() -> dict:
    """Simple liveness check — useful once this gets containerized/deployed."""
    return {"status": "ok"}


@app.post(
    "/tasks",
    response_model=TaskResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["tasks"],
)
def create_task(payload: TaskCreate) -> TaskResponse:
    """Create a new task. Returns 201 with the created resource."""
    task = task_repository.create(payload)
    return task


@app.get("/tasks", response_model=list[TaskResponse], tags=["tasks"])
def list_tasks() -> list[TaskResponse]:
    """List all tasks. Returns 200 with an array (empty array if none exist)."""
    return task_repository.list_all()


@app.get("/tasks/{task_id}", response_model=TaskResponse, tags=["tasks"])
def get_task(task_id: int) -> TaskResponse:
    """Get a single task by id. Returns 404 if it doesn't exist."""
    return task_repository.get(task_id)


@app.put("/tasks/{task_id}", response_model=TaskResponse, tags=["tasks"])
def update_task(task_id: int, payload: TaskUpdate) -> TaskResponse:
    """Partially update a task. Returns 404 if it doesn't exist."""
    return task_repository.update(task_id, payload)


@app.delete("/tasks/{task_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["tasks"])
def delete_task(task_id: int) -> None:
    """Delete a task. Returns 204 (no body) on success, 404 if missing."""
    task_repository.delete(task_id)
    return None


# ---------------------------------------------------------------------------
# BE-06: the LLM triage call as a background job
# ---------------------------------------------------------------------------

def _bg_worker(request: Request) -> JobWorker:
    """The worker pool belongs to the current app's lifespan (loop-bound queue)."""
    worker = getattr(request.app.state, "bg_worker", None)
    if worker is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={"error": "workers_not_running", "message": "Worker pool is unavailable."},
        )
    return worker


@app.post(
    "/jobs/triage",
    response_model=JobAccepted,
    status_code=status.HTTP_202_ACCEPTED,
    tags=["jobs"],
)
def create_triage_job(payload: TriageRequest, request: Request, response: Response) -> JobAccepted:
    """Accept fast, work in the background (BE-06).

    Answers 202 immediately with a job id; a background worker performs the
    LLM triage call and stores the result. Poll GET /jobs/triage/{job_id} for
    the outcome. A repeated idempotency_key returns the SAME job instead of
    creating a duplicate (idempotency). Input validation still returns 400
    naming the field."""
    if payload.idempotency_key:
        existing = bg_store.find_by_idempotency_key(payload.idempotency_key)
        if existing is not None:
            job_id = existing["job_id"]
            accepted = JobAccepted(
                job_id=job_id,
                status=existing["status"],
                status_url=f"/jobs/triage/{job_id}",
            )
            response.headers["Location"] = accepted.status_url
            return accepted

    job_id = f"triage_{uuid.uuid4().hex[:12]}"
    bg_store.create(job_id, payload.message, payload.idempotency_key)
    _bg_worker(request).enqueue(job_id)
    accepted = JobAccepted(job_id=job_id, status="queued", status_url=f"/jobs/triage/{job_id}")
    response.headers["Location"] = accepted.status_url
    return accepted


@app.get("/jobs/triage/{job_id}", response_model=JobResponse, tags=["jobs"])
def get_triage_job(job_id: str) -> JobResponse:
    """Status + result of one background job. 404 if the id is unknown."""
    job = bg_store.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "job_not_found", "message": f"No job with id {job_id}."},
        )
    return JobResponse(**job)
