"""
FlyRank Backend Track — Week 1 Assignment: Build your first API endpoint

Assignment brief (from the cohort kickoff): a basic API with error handling,
returning different responses with different status codes.

This implements a full CRUD API for a "Task" resource — deliberately a bit
more than the bare minimum, structured so it's easy to extend in later weeks
(auth, background jobs, a real database) without a rewrite.

Run locally:
    uvicorn app.main:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

from fastapi import FastAPI, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from fastapi.requests import Request
from dotenv import load_dotenv

from app.exceptions import TaskNotFoundError
from app.models import TaskCreate, TaskUpdate, TaskResponse
from app.repository import task_repository
from src.llm.clients import LLMClient, LLMDisabled, LLMTimeout, LLMUnavailable
from src.llm.schema import TriageRequest, TriageResult
from src.llm.service import LLMInvalidOutput, triage_message
from src.llm.settings import get_settings

load_dotenv()

app = FastAPI(
    title="FlyRank Task API",
    description="Week 1 Backend AI Engineering assignment — a CRUD Task API.",
    version="1.0.0",
)


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------
# Centralizing this here means every endpoint gets consistent error JSON
# without repeating try/except blocks in each route. This is the "error
# handling" half of the assignment brief.

@app.exception_handler(TaskNotFoundError)
async def task_not_found_handler(request: Request, exc: TaskNotFoundError):
    return JSONResponse(
        status_code=status.HTTP_404_NOT_FOUND,
        content={"error": "task_not_found", "message": str(exc)},
    )


@app.exception_handler(RequestValidationError)
async def validation_error_handler(request: Request, exc: RequestValidationError):
    title_errors = ("missing", "value_error", "string_too_short")
    has_title_error = any(
        err.get("loc") == ("body", "title") and err.get("type") in title_errors
        for err in exc.errors()
    )
    if has_title_error:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={
                "error": "validation_error",
                "message": "Title is required and must not be empty.",
            },
        )
    message_errors = ("missing", "value_error", "string_too_short", "string_too_long")
    has_message_error = any(
        err.get("loc") == ("body", "message") and err.get("type") in message_errors
        for err in exc.errors()
    )
    if has_message_error:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={
                "error": "validation_error",
                "message": "'message' is required and must be a non-empty string.",
            },
        )
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"detail": exc.errors()},
    )


# ---------------------------------------------------------------------------
# LLM error handling (A17)
# ---------------------------------------------------------------------------

@app.exception_handler(LLMTimeout)
async def llm_timeout_handler(request: Request, exc: LLMTimeout):
    return JSONResponse(
        status_code=status.HTTP_504_GATEWAY_TIMEOUT,
        content={"error": "llm_timeout", "message": str(exc)},
    )


@app.exception_handler(LLMUnavailable)
async def llm_unavailable_handler(request: Request, exc: LLMUnavailable):
    return JSONResponse(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        content={"error": "llm_unavailable", "message": str(exc)},
    )


@app.exception_handler(LLMDisabled)
async def llm_disabled_handler(request: Request, exc: LLMDisabled):
    return JSONResponse(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        content={"error": "llm_disabled", "message": str(exc)},
    )


@app.exception_handler(LLMInvalidOutput)
async def llm_invalid_output_handler(request: Request, exc: LLMInvalidOutput):
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"error": "invalid_llm_output", "message": str(exc)},
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", tags=["meta"])
def root():
    return {"name": "Task API", "version": "1.0", "endpoints": ["/tasks"]}


@app.get("/health", tags=["meta"])
def health_check() -> dict:
    """Simple liveness check — useful once this gets containerized/deployed."""
    return {"status": "ok"}


@app.post(
    "/tasks",
    response_model=TaskResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["tasks"],
)
def create_task(payload: TaskCreate) -> TaskResponse:
    """Create a new task. Returns 201 with the created resource."""
    task = task_repository.create(payload)
    return task


@app.get("/tasks", response_model=list[TaskResponse], tags=["tasks"])
def list_tasks() -> list[TaskResponse]:
    """List all tasks. Returns 200 with an array (empty array if none exist)."""
    return task_repository.list_all()


@app.get("/tasks/{task_id}", response_model=TaskResponse, tags=["tasks"])
def get_task(task_id: int) -> TaskResponse:
    """Get a single task by id. Returns 404 if it doesn't exist."""
    return task_repository.get(task_id)


@app.put("/tasks/{task_id}", response_model=TaskResponse, tags=["tasks"])
def update_task(task_id: int, payload: TaskUpdate) -> TaskResponse:
    """Partially update a task. Returns 404 if it doesn't exist."""
    return task_repository.update(task_id, payload)


@app.delete("/tasks/{task_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["tasks"])
def delete_task(task_id: int) -> None:
    """Delete a task. Returns 204 (no body) on success, 404 if missing."""
    task_repository.delete(task_id)
    return None


# ---------------------------------------------------------------------------
# A17: LLM endpoint - triage candidate messages
# ---------------------------------------------------------------------------

@app.post(
    "/jobs/triage",
    response_model=TriageResult,
    tags=["jobs"],
)
def triage_job_message(payload: TriageRequest) -> TriageResult:
    """Put an LLM behind the API: classify a candidate message into one of
    four closed categories. Returns 400 for bad input, 503 when the LLM is
    disabled/unavailable, 504 on timeout, 422 when the LLM output does not
    validate even after one repair."""
    client = LLMClient(cfg=get_settings())
    return triage_message(payload.message, client=client)
